### ISSUE TITLE
Inquiry Regarding GPU Memory and Number Requirements and Training Duration

### ISSUE THREAD

**Issue by hero-y** [HadiZayer/eyenerf#1]
I have a few questions regarding the computational resources required to do so.

1. GPU Memory Requirement: Could you please specify the amount of GPU memory required for training the models discussed in the paper? I would appreciate knowing if there are any specific GPU models that are recommended.

2. Number of GPUs: How many GPUs are needed to achieve the results presented in the paper? If it's scalable, could you provide a guideline on how the number of GPUs might affect the training process?

3. Training Duration: What is the approximate training time for the models using the recommended setup? Is this time frame based on a specific GPU configuration?

**Comment by world-from-eyes** [comment]
GPU requirement: It only requires 1 gpu. The memory requirement is not very significant. We have tried it with NVIDIA A4000, A5000, and A6000

Training duration: you can start seeing reasonable output within 2 minutes, and the full 30,000 training steps take sometime between 15 mins and 20 mins
